InventoryManagement/force-app/src/objects/Cycle_Count__c.object
<CustomObject>
    <fields>
        <fullName>Active_Count__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active Count</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Actual_Quantity__c</fullName>
        <label>Actual Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cycle_Count_Version__c</fullName>
        <label>Cycle Count Version</label>
        <referenceTo>Cycle_Count_Version__c</referenceTo>
        <relationshipName>Cycle_Counts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Overall_Quantity__c</fullName>
        <label>Overall Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Item__c</fullName>
        <label>Product Item</label>
        <referenceTo>ProductItem</referenceTo>
        <relationshipName>CycleCounts_del</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Recount_Needed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recount Needed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Serialized_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Serialized Product</label>
        <referenceTo>SerializedProduct</referenceTo>
        <relationshipName>Cycle_Counts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Listed_Quantity__c</fullName>
        <label>Total Listed Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Variance__c</fullName>
        <formula>Serialized_Product__r.Variance__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Variance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Cycle Count Entry</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Cycle Count Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cycle Count Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

InventoryManagement/force-app/src/objects/Cycle_Count_Date__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cycle_Count_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <label>Cycle Count Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location</referenceTo>
        <relationshipLabel>Cycle Count Dates</relationshipLabel>
        <relationshipName>Cycle_Count_Dates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Locations__c</fullName>
        <label>Locations</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NorCal</fullName>
                </value>
                <value>
                    <fullName>Nor Cal - Citrus Heights</fullName>
                </value>
                <value>
                    <fullName>Vehicle 1 - Ria&apos;s Location</fullName>
                </value>
                <value>
                    <fullName>Arizona Serialized Products</fullName>
                </value>
                <value>
                    <fullName>Vehicle 02 - Sushant</fullName>
                </value>
                <value>
                    <fullName>Test location</fullName>
                </value>
                <value>
                    <fullName>SoCal - Santa Ana</fullName>
                </value>
                <value>
                    <fullName>V250 - Chevy Hemi</fullName>
                </value>
                <value>
                    <fullName>V50- test van</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <label>Products</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Tigos/UKT Retrofit</fullName>
                </value>
                <value>
                    <fullName>INVRTR ACCSSRY - OPTMZR - SOLAREDGE - P505</fullName>
                </value>
                <value>
                    <fullName>RMA - INVRTR - STRNG - SOLAREDGE - SE3800A-US</fullName>
                </value>
                <value>
                    <fullName>RCKNG &amp; MNTNG - WR MNGMNT - DOTTIE - CABLE TIE</fullName>
                </value>
                <value>
                    <fullName>40amp Breaker</fullName>
                </value>
                <value>
                    <fullName>INVRTR - STRNG - SMA - SUNNY BOY 3.0-US-41</fullName>
                </value>
                <value>
                    <fullName>RMA - New Unit/s Installation</fullName>
                </value>
                <value>
                    <fullName>BOS - CNNCTR - BUCHANAN - SPLICE CAP COPPER CRIMP CONNECTORS</fullName>
                </value>
                <value>
                    <fullName>Sunrun Cell Swap</fullName>
                </value>
                <value>
                    <fullName>INVRTR MNTRNG - MNTRNG ACCSSRY - NETGEAR - N300 WIFI EXTENDER</fullName>
                </value>
                <value>
                    <fullName>MDL - MDL - LONGI - 335W BOB</fullName>
                </value>
                <value>
                    <fullName>BOS - CRCT BRKR - SOYG - CH280 2-POLE 80-AMP</fullName>
                </value>
                <value>
                    <fullName>RCKNG &amp; MNTNG - CLMP - UNIRAC - UNIVERSAL MID CLAMP</fullName>
                </value>
                <value>
                    <fullName>BOS - CRCT BRKR - SQUARE D - 1 POLE 15A</fullName>
                </value>
                <value>
                    <fullName>Per Diem</fullName>
                </value>
                <value>
                    <fullName>System Installation (R&amp;R)</fullName>
                </value>
                <value>
                    <fullName>TL - TL - X - MC4 CRIMPER</fullName>
                </value>
                <value>
                    <fullName>Tigo Install - (7 or less)</fullName>
                </value>
                <value>
                    <fullName>BOS - CNNCTR - ENPHASE - Q SEAL 10</fullName>
                </value>
                <value>
                    <fullName>$249 Panel Cleaning ≤ 19 Panels</fullName>
                </value>
                <value>
                    <fullName>Additional Labor</fullName>
                </value>
                <value>
                    <fullName>INVRTR MNTRNG - GTWY - ENPHASE - IQ ENVOY 535946</fullName>
                </value>
                <value>
                    <fullName>RMA - INVRTR - STRNG - FIMER - UNO-DM-3.3-TL-PLUS-US</fullName>
                </value>
                <value>
                    <fullName>RMA - INVRTR MNTRNG - COMM CARD - SOLAREDGE - FLD-1PH-PRT-03</fullName>
                </value>
                <value>
                    <fullName>BOS - CNNCTR - BUCHANAN - SPLICE CAP INSULATOR</fullName>
                </value>
                <value>
                    <fullName>RMA - INVRTR - STRNG - FRONIUS - PRIMO 5.0-1 (240V)</fullName>
                </value>
                <value>
                    <fullName>SPPLY - SFTY - X - 18&apos; 5IN1 MULTI-POSITION LADDER</fullName>
                </value>
                <value>
                    <fullName>SPPLY - OTHR - ORANGE HOME DEPOT BUCKET</fullName>
                </value>
                <value>
                    <fullName>RCKNG &amp; MNTNG - CLMP - PROSOLAR - 1.481 - 1.520 BONDING END CLAMP</fullName>
                </value>
                <value>
                    <fullName>Firmware Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Technicians__c</fullName>
        <label>Technicians</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ria Mittal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cycle Count Date</label>
    <nameField>
        <label>Cycle Count Date Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cycle Count Dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InventoryManagement/force-app/src/objects/Cycle_Count_Version__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cycle_Count_Date__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cycle Count Date</label>
        <referenceTo>Cycle_Count_Date__c</referenceTo>
        <relationshipName>Cycle_Count_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location</referenceTo>
        <relationshipName>Cycle_Count_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Cycle_Count_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cycle Count Item</label>
    <nameField>
        <label>Cycle Count Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cycle Count Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InventoryManagement/force-app/src/objects/Location.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

InventoryManagement/force-app/src/objects/ProductItem.object
<CustomObject>
</CustomObject>

objects/ProductItem.object
    <fields>
        <fullName>Overall_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Quantity remaining from all unused serialized products.</inlineHelpText>
        <label>Overall Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

InventoryManagement/force-app/src/objects/ProductTransfer.object
<CustomObject>
    <fields>
        <fullName>Serialized_Product_Id__c</fullName>
        <label>Serialized Product Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

InventoryManagement/force-app/src/objects/SerializedProduct.object
<CustomObject>
    <fields>
        <fullName>Total_Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Original Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/SerializedProduct.object
    <fields>
        <fullName>Overall_Quantity__c</fullName>
        <label>Remaining Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

objects/SerializedProduct.object
    <fields>
        <fullName>Variance__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Variance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

InventoryManagement/force-app/src/classes/CycleCountHelper.cls
/**
* @File Name : CycleCountHelper.cls
* @Description :
* @Author : Ria Mittal
* @Last Modified By : Ria Mittal
* @Last Modified On : February 17, 2025
* @Modification Log :
* Latest Code Coverage from CycleCountHelperTest = 93%
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | February 17, 2025 |   | Initial Version
**/

public class CycleCountHelper {
	
	public static void createBulkCycleCountVersionRecords(List<Cycle_Count_Date__c> newList){

		List<Cycle_Count_Version__c> cycle_count_versions = new List<Cycle_Count_Version__c>();
		for(Cycle_Count_Date__c ccd : newList){

			List<String> locations = ccd.Locations__c.split(';');
            List<String> technicians = ccd.Technicians__c.split(';');
			List<String> products = ccd.Products__c.split(';');
            Map<String, String> locationMap = new Map<String, String>();
            Map<String, String> productMap = new Map<String, String>();
            
            for(Product2 p : [Select Id, Name From Product2 Where Id In :products]){
                productMap.put(p.Id, P.Name);
            }
            for(ServiceResource sr : [Select Id, Name, LocationId From ServiceResource Where IsActive = true And Id In :technicians]){
                locations.add(sr.LocationId);
            }
            for(Schema.Location loc : [Select Id, Name From Location Where Id In :locations]){
                locationMap.put(loc.Id, loc.Name);
            }


            
			for(String loc : locations){
				for(String prod : products){
                    String name = locationMap.get(loc) + ' - ' + productMap.get(prod);
                    if(name.length() > 79) { 
                        name = name.substring(0,79);
                    }
					Cycle_Count_Version__c ccv = new Cycle_Count_Version__c();
					ccv.Cycle_Count_Date__c = ccd.Id;
					ccv.Location__c = loc;
					ccv.Product__c = prod;
					ccv.Active__c = true;
                    // ccv.Name = name;
					cycle_count_versions.add(ccv);
				}
			}
		}
		if(cycle_count_versions.size() > 0){
			insert cycle_count_versions;
		}
	}
    
    public static void createBulkCycleCountRecords(List<Cycle_Count_Version__c> newList){ 
    	System.debug('@@cycle count creation ');
        Map<String, ProductItem> mapOfLocationAndProducts = new Map<String, ProductItem>();
        Map<String, Boolean> mapOfSerializedPIOrNot = new Map<String, Boolean>();
        for(ProductItem pi : [Select Id, LocationId, Product2Id, IsProduct2Serialized, QuantityOnHand, (Select Id, Total_Quantity__c From SerializedProducts) From ProductItem]){
            mapOfLocationAndProducts.put(pi.LocationId + '##' + pi.Product2Id, pi);
            mapOfSerializedPIOrNot.put(pi.Id, pi.IsProduct2Serialized);
        }
        
        List<Cycle_Count__c> cycleCountList = new List<Cycle_Count__c>();
        List<ProductItem> piToInsert = new List<ProductItem>();
        Map<String, Cycle_Count_Version__c> mapOfCCV = new Map<String, Cycle_Count_Version__c>();
        for(Cycle_Count_Version__c ccv : newList){
            if(ccv.Location__c != null && ccv.Product__c != null) {
                String key = ccv.Location__c + '##' + ccv.Product__c;
                mapOfCCV.put(key, ccv);
                if(mapOfLocationAndProducts.containsKey(key)) {
                    if(mapOfSerializedPIOrNot.get(mapOfLocationAndProducts.get(key).Id) == true) {
                        for(SerializedProduct sp : mapOfLocationAndProducts.get(key).SerializedProducts){
                            Cycle_Count__c cc = new Cycle_Count__c();
                            cc.Product_Item__c = mapOfLocationAndProducts.get(key).Id;
                            cc.Cycle_Count_Version__c = ccv.Id;
                            cc.Active_Count__c = true;
                            cc.Serialized_Product__c = sp.Id;
                            cc.Total_Listed_Quantity__c = sp.Total_Quantity__c;
                            cycleCountList.add(cc);
                        }
                    }
                    else {
                        Cycle_Count__c cc = new Cycle_Count__c();
                        cc.Product_Item__c = mapOfLocationAndProducts.get(key).Id;
                        cc.Cycle_Count_Version__c = ccv.Id;
                        cc.Active_Count__c = true;
                        cc.Total_Listed_Quantity__c = mapOfLocationAndProducts.get(key).QuantityOnHand;
                        cycleCountList.add(cc);
                    }
                }
                else {
                    ProductItem pi = new ProductItem();
                    pi.LocationId = ccv.Location__c;
                    pi.Product2Id = ccv.Product__c;
                    pi.QuantityOnHand = 0;
                    piToInsert.add(pi);
                    
                }
            }
            
        }
        if(piToInsert.size() > 0){
            insert piToInsert;
            for(ProductItem pi : piToInsert) {
                
                if(mapOfCCV.containsKey(pi.LocationId + '##' + pi.Product2Id)) {
                    Cycle_Count__c cc = new Cycle_Count__c();
                    cc.Product_Item__c = pi.Id;
                    cc.Cycle_Count_Version__c = mapOfCCV.get(pi.LocationId + '##' + pi.Product2Id).Id;
                    cc.Active_Count__c = true;
                    cc.Total_Listed_Quantity__c = 0;
                    cycleCountList.add(cc);
                }
            }
        }
        if(cycleCountList.size() > 0){
            System.debug('@@inserting cycle counts');
            insert cycleCountList;
        }
    } 
    
    public static void updateRelatedCCV(List<Cycle_Count__c> newList, Map<Id,Cycle_Count__c> oldMap ) {
        List<Cycle_Count_Version__c> versionsToUpdate = new List<Cycle_Count_Version__c>();
        for(Cycle_Count__c cc : newList) { 
            if(cc.Total_Listed_Quantity__c == cc.Actual_Quantity__c){
                Cycle_Count_Version__c ccv = new Cycle_Count_Version__c();
                ccv.Id = cc.Cycle_Count_Version__c;
                ccv.Completed__c = True;
                versionsToUpdate.add(ccv);
                
            }
            else if(cc.Recount_Needed__c == true && oldMap.get(cc.Id).Recount_Needed__c == false){
                Cycle_Count_Version__c ccv = new Cycle_Count_Version__c();
                ccv.Id = cc.Cycle_Count_Version__c;
                ccv.Completed__c = false;
                versionsToUpdate.add(ccv);
            }
        }
        if(versionsToUpdate.size() > 0) {
            update versionsToUpdate;
        }
    }

    public static void afterApprovalAutomations(List<Cycle_Count__c> newList, Map<Id,Cycle_Count__c> oldMap) {

        Set<Id> ccIds = new Set<Id>();
        Set<Id> spIds = new Set<Id>();
       
        for(Cycle_Count__c cc : newList){
            if(cc.Approved__c != oldMap.get(cc.Id).Approved__c) { 
                ccIds.add(cc.Id);
                if(cc.Serialized_Product__c != null && cc.Completed__c == True && 
                    (cc.Technician_Inventory_Person__c == NULL || cc.Technician_Inventory_Person__c == '')) {
                    spIds.add(cc.Serialized_Product__c);
                }

            }
        }

        //Mark un-scanned items as LOST
        List<SerializedProduct> spList = new List<SerializedProduct>();
        for(SerializedProduct sp : [Select ID, Status  From SerializedProduct Where Id In :spIds]) {
            sp.Status = 'Lost';
            spList.add(sp);
        }
        if(spList.size() > 0){
            update spList;
        }

    }

    public static void beforeUpdateAutomations(List<Cycle_Count__c> newList, Map<Id,Cycle_Count__c> oldMap) {
        
        Set<Id> variedSPs = new Set<Id>();
        Map<Id, Cycle_Count__c> spVsCompletionTime = new Map<Id, Cycle_Count__c>();
        for(Cycle_Count__c cc : newList){

            if(cc.Total_Listed_Quantity__c == cc.Actual_Quantity__c) {
                 cc.Approved__c = true;
            }
            if(cc.Approved__c != oldMap.get(cc.Id).Approved__c) { 
            
                //Check for transactions in between approval and completion
                // if(cc.Serialized_Product__c != null && cc.Variance__c > 0 && cc.Completion_DateTime__c < System.now()){
                //     variedSPs.add(cc.Serialized_Product__c);
                //     spVsCompletionTime.put(cc.Serialized_Product__c, cc);
                // }
            }
        }

        List<Cycle_Count__c> ccToUpdate = new List<Cycle_Count__c>();
        Set<Id> transferedSP = new Set<Id>();
        //Check for transactions in between approval and completion
        System.debug('@@variedSPs' + variedSPs);
        // List<ProductTransfer> pt = [Select Id,Serialized_Product_Id__c from ProductTransfer Where Serialized_Product_Id__c In :spVsCompletionTime.keySet()];
        // for(ProductTransfer p : pt) {
        //     if(p.CreatedDate > spVsCompletionTime.get(p.Serialized_Product_Id__c).Completion_DateTime__c) { 
        //         transferedSP.add(p.Serialized_Product_Id__c);
        //     }
        // }

        // for(SerializedProduct sp : [Select Id, Overall_Quantity__c From SerializedProduct Where Id in :transferedSP]) {
            // Cycle_Count__c cc = spVsCompletionTime.get(sp.Id);
            // cc.Actual_Quantity__c = sp.Overall_Quantity__c;
            // ccToUpdate.add(cc);
        // }

        // if(ccToUpdate.size() > 0){
        //     update ccToUpdate;
        // }

    }
}