InventoryManagement/force-app/src/objects/Cycle_Count__c.object
<CustomObject>
    <fields>
        <fullName>Cycle_Count_Version__c</fullName>
        <label>Cycle Count Version</label>
        <referenceTo>Cycle_Count_Version__c</referenceTo>
        <relationshipName>Cycle_Counts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Type_Sub__c</fullName>
        <formula>TEXT(Product_Item__r.Product2.Product_Type_Sub__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type (Sub)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recount_Needed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recount Needed</label>
        <type>Checkbox</type>
    </fields>
    <label>Cycle Count Entry</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Cycle Count Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cycle Count Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

InventoryManagement/force-app/src/objects/Cycle_Count_Date__c.object
<CustomObject>
    <fields>
        <fullName>Cycle_Count_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <label>Cycle Count Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Type_Sub__c</fullName>
        <label>Product Type (Sub)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Test</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cycle Count Date</label>
    <nameField>
        <label>Cycle Count Date Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cycle Count Dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InventoryManagement/force-app/src/objects/Cycle_Count_Version__c.object
<CustomObject>
    <fields>
        <fullName>Cycle_Count_Date__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cycle Count Date</label>
        <referenceTo>Cycle_Count_Date__c</referenceTo>
        <relationshipName>Cycle_Count_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cycle Count Item</label>
    <nameField>
        <label>Cycle Count Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cycle Count Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InventoryManagement/force-app/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Type_Sub__c</fullName>
        <description>Sub Category of the Product Type</description>
        <inlineHelpText>Sub Category of the Product Type</inlineHelpText>
        <label>Product Type (Sub)</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accessory</fullName>
                </value>
                <value>
                    <fullName>Adapter</fullName>
                </value>
                <value>
                    <fullName>Attachment</fullName>
                </value>
                <value>
                    <fullName>Ballast Bay</fullName>
                </value>
                <value>
                    <fullName>Base Mount</fullName>
                </value>
                <value>
                    <fullName>Battery</fullName>
                </value>
                <value>
                    <fullName>Battery BOS</fullName>
                </value>
                <value>
                    <fullName>Block</fullName>
                </value>
                <value>
                    <fullName>Bolt</fullName>
                </value>
                <value>
                    <fullName>Brace Assembly</fullName>
                </value>
                <value>
                    <fullName>Bracket</fullName>
                </value>
                <value>
                    <fullName>Busbar</fullName>
                </value>
                <value>
                    <fullName>Cable</fullName>
                </value>
                <value>
                    <fullName>Cap</fullName>
                </value>
                <value>
                    <fullName>Circuit Breaker</fullName>
                </value>
                <value>
                    <fullName>Clamp</fullName>
                </value>
                <value>
                    <fullName>Clip</fullName>
                </value>
                <value>
                    <fullName>Combiner Box</fullName>
                </value>
                <value>
                    <fullName>Communication Card</fullName>
                </value>
                <value>
                    <fullName>Conduit</fullName>
                </value>
                <value>
                    <fullName>Conduit Mount</fullName>
                </value>
                <value>
                    <fullName>Connector</fullName>
                </value>
                <value>
                    <fullName>Controller</fullName>
                </value>
                <value>
                    <fullName>Converter</fullName>
                </value>
                <value>
                    <fullName>Disconnect</fullName>
                </value>
                <value>
                    <fullName>Display</fullName>
                </value>
                <value>
                    <fullName>Electrical Accessory</fullName>
                </value>
                <value>
                    <fullName>Electric Board</fullName>
                </value>
                <value>
                    <fullName>Enclosure</fullName>
                </value>
                <value>
                    <fullName>EV Charger</fullName>
                </value>
                <value>
                    <fullName>Module</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <description>Main Category of Product</description>
        <inlineHelpText>Main Category of Product</inlineHelpText>
        <label>Product Type (Main)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Module</fullName>
                </value>
                <value>
                    <fullName>Inverter</fullName>
                </value>
                <value>
                    <fullName>Inverter Monitoring</fullName>
                </value>
                <value>
                    <fullName>Inverter Accessory</fullName>
                </value>
                <value>
                    <fullName>Balance Of System (BOS)</fullName>
                </value>
                <value>
                    <fullName>Racking and Mounting</fullName>
                </value>
                <value>
                    <fullName>Battery</fullName>
                </value>
                <value>
                    <fullName>Battery Accessory</fullName>
                </value>
                <value>
                    <fullName>Charge Controller</fullName>
                </value>
                <value>
                    <fullName>Tool</fullName>
                </value>
                <value>
                    <fullName>Supply</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

InventoryManagement/force-app/src/objects/ProductItem.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <formula>Product2.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type_Sub__c</fullName>
        <description>Product Type (Sub)</description>
        <label>Product Type (Sub)</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

InventoryManagement/force-app/src/objects/SerializedProduct.object
<CustomObject>
    <fields>
        <fullName>Total_Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Original Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

InventoryManagement/force-app/src/classes/CycleCountControllerTest.cls
@isTest
public class CycleCountControllerTest {
	 @testSetup
    static void setupData() {
       
        Schema.Location loc1 = new Schema.Location(Name = 'Test Location 1', LocationType='Warehouse',IsInventoryLocation=true,IsMobile=true);
        insert loc1;

        Schema.Location loc2 = new Schema.Location(Name = 'Test Location 2', LocationType='Warehouse',IsInventoryLocation=true,IsMobile=true);
        insert loc2;

        Product2 prod1 = new Product2(Name = 'Test Product 1', 
                                      ProductCode = 'TP1',
                                      IsSerialized=true,
                                      IsActive=true,
                                      Family='Inventory',
                                      Product_Type__c = 'Module',
                                      Product_Type_Sub__c = 'Module'
                                     );
        insert prod1;

         ProductItem pi1 = new ProductItem(
            Product2Id = prod1.Id,
            LocationId = loc1.Id,
            QuantityOnHand = 0
        );
        insert pi1;
        
        SerializedProduct sp1 = new SerializedProduct(
            SerialNumber = 'SP001',
            Product2Id = prod1.Id,
            ProductItemId = pi1.Id,
            Total_Quantity__c=100
        );
        insert sp1;

        SerializedProduct sp2 = new SerializedProduct(
            SerialNumber = 'SP002',
            Product2Id = prod1.Id,
            ProductItemId = pi1.Id,
            Total_Quantity__c=100
        );
        insert sp2;

        /* Data for NONSP*/
        Product2 prod2 = new Product2(Name = 'Test Product 2', 
                                      ProductCode = 'TP2',
                                      IsSerialized=false,
                                      IsActive=true,
                                      Family='Inventory',
                                      Product_Type__c = 'Module',
                                      Product_Type_Sub__c = 'Module');
        insert prod2;

         ProductItem pi2 = new ProductItem(
            Product2Id = prod2.Id,
            LocationId = loc1.Id,
            QuantityOnHand = 10
        );
        insert pi2;

        ProductItem pi3 = new ProductItem(
            Product2Id = prod2.Id,
            LocationId = loc2.Id,
            QuantityOnHand = 10
        );
        insert pi3;

        ServiceResource sr1 = new ServiceResource(
            Name='TestSR',
            LocationId = loc1.Id,
            RelatedRecordId = UserInfo.getUserId()
        );
        insert sr1;
    }

    /*@isTest
    static void testCombinedCycleCount() {
        Test.startTest();

        List<ProductItem> pi = [Select Id, ProductItemNumber From ProductItem Where IsProduct2Serialized = false];
        List<String> barcodes = new List<String>{
            'SP001#$#100#$#30',
            'SP002#$#100#$#30',
            pi[0].ProductItemNumber + '#$#10#$#7',
            pi[1].ProductItemNumber + '#$#10#$#7'
        };
   
        Schema.Location loc = [Select Id From Location Where Name = 'Test Location 1' LIMIT 1];
        CycleCountController.combinedCycleCount(barcodes, loc.Id);
		
        Test.stopTest();
    }*/

    @isTest
    static void testFetchTotalQuantityForScannedProduct() {
        Test.startTest();
		
        Schema.Location loc = [Select Id From Location LIMIT 1];
        ServiceResource sr = [Select Id From ServiceResource LIMIT 1];
        
        Decimal totalQuantity = CycleCountController.fetchTotalQuantityForScannedProduct('SP001');
        Decimal totalQuantity1 = CycleCountController.fetchTotalQuantityForScannedProduct([Select Id, ProductItemNumber, Name__c From ProductItem Where IsProduct2Serialized = true LIMIT 1].Name__c);
        System.assertEquals(100, totalQuantity, 'Expected total quantity for Serialized Product');
        
        CycleCountController.fetchProductNameForScannedProduct('SP001', loc.Id);
		CycleCountController.fetchProductNameForScannedProduct([Select Id, ProductItemNumber, Name__c From ProductItem Where IsProduct2Serialized = true LIMIT 1].Name__c, loc.Id);
        
        CycleCountController.fetchActualQuantityForScannedProduct('SP001', loc.Id);
        CycleCountController.fetchActualQuantityForScannedProduct([Select Id, ProductItemNumber, Name__c From ProductItem Where IsProduct2Serialized = true LIMIT 1].Name__c, loc.Id);
        
        CycleCountController.fetchLocation(loc.Id);
        CycleCountController.fetchTechnicianDetails(sr.Id);
        
        CycleCountController.getAllProductFamily();
        CycleCountController.getAllProductTypesMain();
        CycleCountController.getAllProductTypesSub();
        CycleCountController.getAllLocations();
        CycleCountController.markComplete();
        CycleCountController.getAllProductDetails('Inventory', 'Module', 'Module');
        
        Test.stopTest();
    }
    
    @isTest
    public static void testCCD(){
        Schema.Location loc = [Select Id From Location LIMIT 1];
        ServiceResource sr = [Select Id From ServiceResource LIMIT 1];
        
        CycleCountController.CycleCountDateWrapper ccdWrapper = new CycleCountController.CycleCountDateWrapper();
        ccdWrapper.StartDate = '2025-03-03T11:45:00.000Z'; //DateTime.now().format();
        ccdWrapper.EndDate = '2025-03-10T10:45:00.000Z';//(DateTime.now()+1).format();
        ccdWrapper.Locations = (String)loc.Id;
        ccdWrapper.Products = (String)([Select Id From product2 LIMIT 1].Id);
        ccdWrapper.ProductFamily = 'Inventory';
        ccdWrapper.ProductTypeMain = 'Module';
        ccdWrapper.ProductTypeSub = 'Module';
         ccdWrapper.Technicians = sr.Id;
        ccdWrapper.TimeFrame = 'Weekly';
        String ccdJson = JSON.serialize(ccdWrapper);
        CycleCountController.saveCycleCountDates(ccdJson);
        
        List<ProductItem> pi = [Select Id, ProductItemNumber, Name__c From ProductItem Where IsProduct2Serialized = false];
        List<String> barcodes = new List<String>{
            'SP001#$#100#$#30',
            'SP002#$#100#$#30',
            pi[0].Name__c + '#$#10#$#7',
            pi[1].Name__c + '#$#10#$#7'
        };
            
        Schema.Location loc1 = [Select Id From Location Where Name = 'Test Location 1' LIMIT 1];
        CycleCountController.combinedCycleCount(barcodes, loc1.Id);
        CycleCountController.combinedPullMaterials(barcodes, loc1.Id, True, sr.Id);
        
        Cycle_Count__c cc = [ Select Id, Recount_Needed__c, Cycle_Count_Version__r.Cycle_Count_Date__c From Cycle_Count__c LIMIT 1];
        cc.Recount_Needed__c = True;
        update cc;
        
		CycleCountController.sentRecountNotification(cc.Cycle_Count_Version__r.Cycle_Count_Date__c, new String[]{});
        
        CycleCountController.checkForDuplicates('SP001', loc1.Id, 10);
        
    }

 

}